### ISSUE TITLE
Adding a directory to mongodb database

### ISSUE THREAD

**Issue by kaseykwong** [kaseykwong/bme590final#18]
Is there a proper way to create a directory of folders in a mongodb database to store all of the head impact binary files into the remote database? right now, shown below and in the server.py file, I'm using lists and lists of lists to emulate folders like you would see in a Finder window or Windows Explorer window. In this case, the 1st pin_number in the pin_number list corresponds to the first list of dates. But with this method, there isn't a clear "path name" for the file such as /user/docs/data/2018/person2/2018may5/file2 and the post-storage code that Dr. Luck is using requires that path to be part of the input to his current Matlab analysis code. 
`class Data(MongoModel):
    season = fields.DateTimeField()
    pin_number = fields.ListField(field=fields.IntegerField())
    dates = fields.ListField(field=fields.ListField(field=fields.DateTimeField()))
    bin_files = fields.ListField(field=fields.ListField(field=fields.ListField(field=fields.BinaryField())))`

**Comment by mlp6** [comment]
Good question... as you are encountering, your "list of list" approach get cumbersome very quickly _and_ it is tricky to re-organize that structure once created.  One approach that I have used--though very dependent on use case and why you want to preserve this path information--is to store a `path` field that is a string that you can then query and parse based on the delimiting character that you use in the path.  In this approach, you don't have your actual storage structure represent the path, but you have one long list of files, and each has an associated path.  

An intermediate approach is to figure out what information is being stored in the path (what is the organizational scheme), and then capture those levels of the directory structure as different fields that have different values such that you can reconstruct the path.  This is actually my preferred approach over a path string since it allows you to very easily re-organize data later, including changing how you group the data, etc.  This is also very amenable to reading in data from the database into [DataFrames](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.html).

**Comment by kaseykwong** [comment]
So with the intermediate approach you mentioned, I could instead create, say a "file" class, that has pin number, encoded binary file, date parameters. And when downloading the data from the device, I could instead just save each binary file as an individual "file" object into my database? It might be out of scope of the project, but if one were to pull a particular file and they input a path string, a potential function could deconstruct that string and search for the file object that matches those path values and return the encoded binary file?
